import { Nunito_Sans } from 'next/font/google';
import './global.css';

export const metadata = {
  title: 'Welcome to Meta mind',
  description: 'Generated by create-nx-workspace',
};

const nutinoSans = Nunito_Sans({
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={nutinoSans.className}>{children}</body>
    </html>
  );
}
